# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  #config.vm.network :forwarded_port, host: 4444, guest: 1122
  config.vm.synced_folder "shared", "/vagrant"
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
  end


  config.vm.provision "shell", path: "bootstrap.sh"


  config.vm.define 'development' do |development|
      development.vm.hostname = 'dev.wesovi.com'
      development.vm.network "private_network", ip: "192.168.77.21"
  end


  config.vm.provision :ansible do |ansible|
      ansible.sudo           = true
      ansible.limit          = 'all'
      ansible.playbook       = "ansible/playbook.yml"
      ansible.verbose        = "vvv"
      #ansible.inventory_path = "ansible/environments/development"
  end

end